-- Vytvorenie schémy
CREATE SCHEMA IF NOT EXISTS DOG_DB.covid;
USE SCHEMA DOG_DB.covid;

-- Staging tabuľky
CREATE OR REPLACE TABLE WHO_TIMESERIES AS
SELECT * 
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.WHO_TIMESERIES;

CREATE OR REPLACE TABLE WHO_DAILY_REPORT AS
SELECT * 
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.WHO_DAILY_REPORT;

CREATE OR REPLACE TABLE WHO_REPORTS AS
SELECT * 
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.WHO_SITUATION_REPORTS;
